import {useVolunteerUpdates} from './volunteersModel';
import React,{useEffect,useState}from'react';
import{CalendarDays,Check,Lock,Plus}from'lucide-react';
import{volunteers}from'./Schedule';
import{sundays,votingOpen,type AvailabilityPoll,type AvailabilityAnswer}from'./availabilityModel';
type Viewer={role:string;volunteer_id?:string};
const labels={yes:'Posso participar',no:'Não posso',maybe:'Ainda não sei'};
const fmt=(date:string)=>new Date(date+'T12:00:00').toLocaleDateString('pt-BR');
async function call(path='',method='GET',body?:unknown){const r=await fetch('/api/availability'+path,{method,headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const d:any=await r.json();if(!r.ok)throw Error(d.error);return d;}
export default function Availability({user}:{user:Viewer}){useVolunteerUpdates();
 const manager=['admin','team'].includes(user.role);
 const[polls,setPolls]=useState<AvailabilityPoll[]>([]),[pollId,setPollId]=useState(''),[draft,setDraft]=useState<Record<string,AvailabilityAnswer>>({}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[creating,setCreating]=useState(false),[month,setMonth]=useState('2026-11'),[deadline,setDeadline]=useState('2026-10-25'),[dates,setDates]=useState<string[]>(sundays('2026-11'));
 const poll=polls.find(p=>p.id===pollId),person=volunteers.find(v=>v.id===user.volunteer_id),open=!!poll&&votingOpen(poll);
 async function refresh(selectId?:string){const d=await call();setPolls(d.polls);if(selectId)setPollId(selectId);else if(!pollId&&d.polls[0])setPollId(d.polls[0].id)}
 useEffect(()=>{refresh().catch(e=>setError(e.message))},[]);
 useEffect(()=>{setDraft({...poll?.responses[user.volunteer_id||'']});},[pollId,poll,user.volunteer_id]);
 async function act(fn:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await fn()}catch(e){setError(e instanceof Error?e.message:'Não foi possível concluir.')}finally{setBusy(false)}}
 const responded=poll?volunteers.filter(v=>Object.keys(poll.responses[v.id]||{}).length>0):[];
 return <><div className="heading"><div><p className="eyebrow">PLANEJAMENTO DA EQUIPE</p><h1>Disponibilidade</h1><p>Marque os dias em que pode servir. A equipe decide a escala depois.</p></div>{manager&&<button className="primary" disabled={busy} onClick={()=>setCreating(!creating)}><Plus size={18}/>Abrir votação</button>}</div>
 <div className="availability-rule">Responder à votação não preenche nenhuma vaga. A escala definitiva é montada pela equipe autorizada.</div>
 {error&&<div className="alert error" role="alert">{error}</div>}{notice&&<div className="alert success" role="status">{notice}</div>}
 {creating&&manager&&<section className="panel poll-create"><h2>Nova votação</h2><form onSubmit={e=>{e.preventDefault();void act(async()=>{const d=await call('','POST',{month,deadline,dates});await refresh(d.id);setCreating(false);setNotice('Votação aberta. Nenhuma vaga foi preenchida.')})}}><div className="poll-create-fields"><label>Mês<input type="month" required value={month} onChange={e=>{setMonth(e.target.value);if(e.target.value)setDates(sundays(e.target.value))}}/></label><label>Responder até<input type="date" required value={deadline} onChange={e=>setDeadline(e.target.value)}/></label></div><div className="poll-dates">{(month?sundays(month):[]).map(d=><label className="checkbox" key={d}><input type="checkbox" checked={dates.includes(d)} onChange={e=>setDates(e.target.checked?[...dates,d].sort():dates.filter(date=>date!==d))}/>{fmt(d)}</label>)}</div><div className="actions"><button className="primary" disabled={busy||!dates.length}>Abrir votação</button><button type="button" onClick={()=>setCreating(false)} disabled={busy}>Cancelar</button></div></form></section>}
 <section className="panel"><label className="poll-select">Votação<select value={pollId} onChange={e=>{setPollId(e.target.value);setNotice('');setError('')}} disabled={busy}>{!polls.length&&<option value="">Nenhuma votação aberta</option>}{polls.map(p=><option key={p.id} value={p.id}>{p.month.split('-').reverse().join('/')} · {votingOpen(p)?'Aberta':'Encerrada'}</option>)}</select></label>
 {poll&&<><div className="poll-summary"><span className={`poll-status ${open?'open':''}`}>{open?'Aberta':'Encerrada'}</span><span>Prazo: {fmt(poll.deadline)}</span><span>{responded.length} de {volunteers.length} responderam</span></div><h2>Minha disponibilidade{person?` — ${person.name}`:''}</h2>{!person&&<p>Seu acesso precisa estar vinculado a um voluntário para responder.</p>}{person&&<><div className="availability-rows">{poll.dates.map(d=><article className="availability-date" key={d}><strong><CalendarDays size={17}/>{fmt(d)}</strong><div className="availability-choices">{(['yes','no','maybe']as const).map(choice=><button type="button" key={choice} className={`answer-${choice}${draft[d]===choice?' selected':''}`} aria-pressed={draft[d]===choice} disabled={busy||!open} onClick={()=>setDraft({...draft,[d]:choice})}>{draft[d]===choice&&<Check size={15}/>} {labels[choice]}</button>)}</div></article>)}</div><div className="actions poll-save"><button className="primary" disabled={busy||!open||!Object.keys(draft).length} onClick={()=>void act(async()=>{await call('/'+poll.id+'/responses','PUT',{answers:draft});await refresh();setNotice('Disponibilidade salva. A escala continua sem preenchimento automático.')})}>Salvar disponibilidade</button><button disabled={busy||!open} onClick={()=>{setDraft({...poll.responses[user.volunteer_id||'']});setNotice('Alterações canceladas. Suas respostas anteriores foram mantidas.')}}>Cancelar alterações</button></div>{!open&&<p className="muted">Esta votação foi encerrada. As respostas estão disponíveis para consulta.</p>}</>}
 {manager&&<div className="poll-manager"><button disabled={busy} onClick={()=>void act(async()=>{const d=await call('/'+poll.id+'/blank-schedule','POST',{});setNotice(`${d.added} data(s) adicionada(s) à Escala com cinco vagas livres. Escalas já existentes foram mantidas.`)})}>Criar escala com vagas livres</button>{open&&<button disabled={busy} onClick={()=>{if(confirm('Encerrar esta votação e bloquear novas respostas?'))void act(async()=>{await call('/'+poll.id+'/close','POST',{});await refresh();setNotice('Votação encerrada. A equipe pode montar e editar a escala.')})}}><Lock size={16}/>Encerrar votação</button>}</div>}
 </>}{!poll&&<div className="empty"><CalendarDays size={30}/><h3>Nenhuma votação disponível</h3><p>A equipe pode abrir uma votação para o próximo mês.</p></div>}</section>
 {poll&&<section className="panel availability-results"><h2>Respostas por data</h2>{poll.dates.map(d=><article className="availability-result" key={d}><h3>{fmt(d)}</h3>{(['yes','no','maybe','pending']as const).map(status=>{const people=volunteers.filter(v=>(poll.responses[v.id]?.[d]||'pending')===status);return <div className="availability-result-group" key={status}><strong>{status==='pending'?'Sem resposta':labels[status]} · {people.length}</strong><div className="volunteer-chips">{people.map(v=><span className="volunteer-chip" key={v.id} style={{background:v.color,color:v.text}}>{v.name}</span>)}{!people.length&&<small>Nenhum</small>}</div></div>})}</article>)}<h3>Quem ainda não respondeu</h3><div className="volunteer-chips">{volunteers.filter(v=>!responded.some(x=>x.id===v.id)).map(v=><span className="volunteer-chip" key={v.id} style={{background:v.color,color:v.text}}>{v.name}</span>)}{responded.length===volunteers.length&&<small>Todos responderam.</small>}</div></section>}
 </>;
}
