import React,{useEffect,useState} from 'react';
type Key={id:string;name:string;created_at:string;revoked_at:string|null};
async function api(path='',method='GET',body?:unknown){const r=await fetch('/api/integrations'+path,{method,headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const d:any=await r.json();if(!r.ok)throw Error(d.error||'Não foi possível concluir.');return d}
export default function Integrations(){
 const [keys,setKeys]=useState<Key[]>([]),[endpoints,setEndpoints]=useState<{visitors:string}|null>(null),[name,setName]=useState(''),[secret,setSecret]=useState<{id:string;token:string}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const refresh=async()=>{const d=await api();setKeys(d.keys);setEndpoints(d.endpoints)};
 async function act(fn:()=>Promise<void>){setBusy(true);setError('');setMessage('');try{await fn()}catch(e){setError(e instanceof Error?e.message:'Falha na conexão.')}finally{setBusy(false)}}
 useEffect(()=>{void act(refresh)},[]);
 async function copy(text:string){try{await navigator.clipboard.writeText(text);setMessage('Copiado.')}catch{setError('Não foi possível copiar. Selecione o texto e copie manualmente.')}}
 return <><div className="heading"><div><p className="eyebrow">ADMINISTRAÇÃO</p><h1>Integrações</h1><p>Permita que outro sistema consulte visitantes e presenças.</p></div><button disabled={busy} onClick={()=>void act(refresh)}>Atualizar</button></div>
 {error&&<div className="alert error" role="alert">{error}</div>}{message&&<div className="alert success" role="status">{message}</div>}
 <section className="panel integration-panel"><h2>Link de consulta</h2><p>Um único link reúne nomes, telefones, datas das visitas, total e última visita. Compartilhe o link e uma chave com o responsável pelo sistema de destino. O link sozinho não libera acesso.</p>{endpoints&&<label>Visitantes e presenças<input readOnly value={endpoints.visitors} onFocus={e=>e.target.select()}/><button onClick={()=>void copy(endpoints.visitors)}>Copiar link</button></label>}</section>
 <section className="panel integration-panel"><h2>Gerar chave de acesso</h2><p>Crie uma chave para cada sistema. O acesso permite somente consulta de nomes, telefones e histórico de visitas.</p><form onSubmit={e=>{e.preventDefault();void act(async()=>{const d=await api('','POST',{name});setSecret({id:d.key.id,token:d.token});setName('');setKeys(previous=>[...previous,d.key]);setMessage('Chave criada. Copie e guarde antes de sair desta tela.')})}}><label>Nome do sistema<input required minLength={2} maxLength={80} placeholder="Ex.: Sistema de acompanhamento" value={name} onChange={e=>setName(e.target.value)}/></label><button className="primary" disabled={busy||!!secret}>Gerar chave</button></form>
 {secret&&<div className="integration-secret"><h3>Guarde esta chave</h3><p>Ela será exibida somente agora. Não coloque a chave no link nem em páginas públicas.</p><label>Chave de acesso<textarea readOnly rows={3} value={secret.token} onFocus={e=>e.target.select()}/></label><div className="actions"><button onClick={()=>void copy(secret.token)}>Copiar chave</button><button onClick={()=>setSecret(null)}>Já guardei a chave</button></div></div>}</section>
 <section className="panel integration-panel"><h2>Acessos criados</h2>{!keys.length&&<p>Nenhuma chave criada.</p>}{keys.map(key=><article className="integration-access" key={key.id}><div><strong>{key.name}</strong><small>Criada em {new Date(key.created_at).toLocaleString('pt-BR')} · {key.revoked_at?'Revogada':'Ativa'}</small></div>{!key.revoked_at&&<button className="danger" disabled={busy} onClick={()=>{if(confirm('Revogar este acesso? O sistema que usa esta chave deixará de consultar os dados.'))void act(async()=>{await api('/'+key.id,'DELETE');if(secret?.id===key.id)setSecret(null);await refresh();setMessage('Acesso revogado.')})}}>Revogar acesso</button>}</article>)}</section>
 <section className="panel integration-panel"><h2>Como configurar no outro sistema</h2><ol><li>Consulte o link usando GET e o cabeçalho <code>Authorization: Bearer SUA_CHAVE</code>.</li><li>Os resultados em JSON ficam em <code>dados</code>. Cada visitante inclui <code>id</code>, <code>nome</code>, <code>telefone</code>, <code>datas_visitas</code>, <code>total_visitas</code> e <code>ultima_visita</code>.</li><li>Continue consultando <code>paginacao.proximo_link</code>, com a mesma chave, até ele retornar <code>null</code>. O padrão é 50 registros por página; <code>limite=100</code> permite até 100.</li><li>Para selecionar visitantes que compareceram em um período, use <code>?inicio=2026-10-01&amp;fim=2026-10-31</code>. As datas, o total e a última visita de cada pessoa sempre incluem todo o histórico, mesmo com esse filtro.</li></ol><p>Para manter uma cópia atualizada, consulte as páginas completas periodicamente e substitua a cópia anterior após concluir a consulta. Isso também reflete correções e exclusões. Os resultados podem mudar enquanto a recepção registra novas visitas.</p><p className="muted">Esta tela não envia dados automaticamente. O sistema de destino precisa configurar as consultas. Equipe, escalas, senhas e anotações internas ficam fora da integração.</p></section></>;
}
