import {replaceVolunteers} from './volunteersModel';
import {useVolunteerUpdates} from './volunteersModel';

import Schedule,{volunteers} from './Schedule';
import Availability from './Availability';
import Navigation from './Navigation';
import NextShift from './NextShift';
import VisitorFollowup,{type Followup} from './VisitorFollowup';
import TeamAccess from './TeamAccess';
import Notices from './Notices';
import ExportData from './ExportData';
import Integrations from './Integrations';
import React,{useState,useEffect} from 'react';import{createRoot}from'react-dom/client';import{UserPlus,Users,LogOut,Search,ArrowLeft,Check,CalendarDays,Download}from'lucide-react';import './style.css';
type Visitor={id:string;name:string;phone:string;consent:number;visits_count?:number;last_visit?:string;followup?:Followup};type User={id:string;name:string;role:string;volunteer_id?:string};
async function api(path:string,method='GET',body?:unknown){const r=await fetch('/api'+path,{method,headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const data:any=await r.json();if(!r.ok)throw Error(data.error||'Falha na conexão.');return data;}
const date=(d:string)=>new Date(d+'T12:00:00').toLocaleDateString('pt-BR');const phone=(p:string)=>p.replace(/^(\d{2})(\d{4,5})(\d{4})$/,'($1) $2-$3');
function App(){useVolunteerUpdates();const[user,setUser]=useState<User|null>(null),[loading,setLoading]=useState(true),[tab,setTab]=useState('dashboard'),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[dashboard,setDashboard]=useState<any>(null),[list,setList]=useState<Visitor[]>([]),[query,setQuery]=useState(''),[followupFilter,setFollowupFilter]=useState('all'),[selected,setSelected]=useState<any>(null),[install,setInstall]=useState<any>(null),[online,setOnline]=useState(navigator.onLine);
 const[form,setForm]=useState({name:'',phone:'',consent:false}),[login,setLogin]=useState({email:'',password:''});
 useEffect(()=>{api('/me').then(d=>{replaceVolunteers(d.volunteers);setUser(d.user)}).catch(()=>{}).finally(()=>setLoading(false));const evt=(e:any)=>{e.preventDefault();setInstall(e)};const net=()=>setOnline(navigator.onLine);window.addEventListener('beforeinstallprompt',evt);window.addEventListener('online',net);window.addEventListener('offline',net);return()=>{window.removeEventListener('beforeinstallprompt',evt);window.removeEventListener('online',net);window.removeEventListener('offline',net)}},[]);
 const refresh=async()=>{const d=await api('/dashboard');setDashboard(d);};
 useEffect(()=>{if(!user)return;setError('');if(tab==='dashboard')refresh().catch(e=>setError(e.message));},[user,tab]);
 useEffect(()=>{if(!user||tab!=='visitors')return;let active=true;const t=setTimeout(()=>{api('/visitors?q='+encodeURIComponent(query)).then(d=>{if(active)setList(d.visitors)}).catch(e=>{if(active)setError(e.message)})},200);return()=>{active=false;clearTimeout(t)}},[query,user,tab]);
 async function act(fn:()=>Promise<void>){setBusy(true);setError('');setMessage('');try{await fn()}catch(e){setError(e instanceof Error?e.message:'Falha na conexão.')}finally{setBusy(false)}}
 const go=(next:string)=>{setTab(next);setSelected(null);setError('');setMessage('');if(next==='new')setForm({name:'',phone:'',consent:false})};
 const open=async(id:string)=>act(async()=>{const d=await api('/visitors/'+id);setSelected(d);setForm({name:d.visitor.name,phone:d.visitor.phone,consent:!!d.visitor.consent});setTab('detail')});
 const fields=<><label>Nome completo<input required minLength={2} maxLength={120} autoComplete="name" placeholder="Como podemos chamar você?" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Telefone / WhatsApp<input required inputMode="tel" autoComplete="tel" maxLength={20} placeholder="(11) 99999-9999" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><small>Inclua o DDD. O telefone ajuda a encontrar o cadastro no retorno.</small></label><label className="checkbox"><input type="checkbox" checked={form.consent} onChange={e=>setForm({...form,consent:e.target.checked})}/><span>A pessoa aceita receber mensagens da Igreja Onda pelo WhatsApp.<small>Pergunte ao visitante antes de marcar.</small></span></label></>;
 if(loading)return <div className="loading">Preparando a recepção…</div>;
 if(!user)return <main className="login"><section><div className="brand"><span>BASE<small>RECEPÇÃO · IGREJA ONDA</small></span></div><p className="eyebrow">QUE BOM TER VOCÊ AQUI</p><h1>Acolher começa<br/>com um encontro.</h1><p>Entre com o acesso fornecido pela equipe da Igreja Onda.</p><form onSubmit={e=>{e.preventDefault();act(async()=>{const d=await api('/login','POST',login);replaceVolunteers(d.volunteers);setUser(d.user);setLogin({email:'',password:''});go('dashboard')})}}><label>E-mail<input type="email" required autoComplete="username" value={login.email} onChange={e=>setLogin({...login,email:e.target.value})}/></label><label>Senha<input type="password" required autoComplete="current-password" value={login.password} onChange={e=>setLogin({...login,password:e.target.value})}/></label>{error&&<div role="alert" className="alert error">{error}</div>}<button disabled={busy||!online} className="primary">{busy?'Entrando…':'Entrar na recepção'}</button></form><small>BASE · v1.1.0</small></section><aside><div className="base-poster"><span>BASE</span><h2>Viva o<br/>extraordinário.</h2></div></aside></main>;
 return <div className="app"><aside className="sidebar"><div className="brand"><span>BASE<small>RECEPÇÃO · IGREJA ONDA</small></span></div><div className="nav-label">ACOLHIMENTO</div><Navigation tab={tab} role={user.role} onNavigate={go}/><div className="sidebar-bottom"><p>{user.name}<small>{user.role==='admin'?'Administrador':user.role==='team'?'Equipe autorizada':'Voluntário'}</small></p><button onClick={()=>act(async()=>{await api('/logout','POST');setUser(null);setList([]);setSelected(null);setDashboard(null)})}><LogOut size={18}/>Sair</button><small>Versão 1.1.0</small></div></aside><main className="content"><header><span>Igreja Onda / BASE</span>{install&&<button onClick={async()=>{await install.prompt();setInstall(null)}}><Download size={17}/>Instalar aplicativo</button>}<span className="avatar">{user.name[0]}</span><button aria-label="Sair da conta" onClick={()=>act(async()=>{await api('/logout','POST');setUser(null);setList([]);setSelected(null);setDashboard(null)})}><LogOut size={17}/></button></header>{!online&&<div role="alert" className="alert error">Sem conexão. Conecte-se à internet para consultar e registrar visitas.</div>}{error&&<div role="alert" className="alert error">{error}</div>}{message&&<div role="status" className="alert success"><Check size={18}/>{message}</div>}
 {tab==='dashboard'&&<><div className="heading"><div><p className="eyebrow">BASE · IGREJA ONDA</p><h1>Um lugar para acolher.</h1><p>Organize as visitas e acompanhe quem está chegando.</p></div><button className="primary" onClick={()=>go('new')}><UserPlus size={19}/>Nova visita</button></div><section className="welcome"><div><span>BASE · ACOLHIMENTO</span><h2>Viva o<br/>extraordinário.</h2><p>Cada nome importa. Cada encontro também.</p></div><span className="base-mark" aria-hidden="true">B</span></section><NextShift key={user.id+user.volunteer_id} volunteerId={user.volunteer_id} onOpen={()=>go('schedule')}/><Notices key={'recent-'+user.id+user.volunteer_id} role={user.role} compact onOpen={()=>go('notices')}/><div className="stats">{[['Visitas hoje',dashboard?.today],['Primeiras visitas hoje',dashboard?.first],['Retornos hoje',dashboard?.returns],['Visitantes cadastrados',dashboard?.total]].map(([label,value])=><article key={label}><span>{label}</span><strong>{value??'—'}</strong></article>)}</div><section className="panel"><div className="section-title"><h2>Quem chegou hoje</h2><span><CalendarDays size={16}/>{dashboard?date(dashboard.date):'Hoje'}</span></div><p className="muted">Primeira visita e retorno contam uma vez por pessoa no dia.</p>{dashboard?.recent?.length?<div className="people">{dashboard.recent.map((v:Visitor)=><button className="person" key={v.id} onClick={()=>open(v.id)}><span className="person-avatar">{v.name[0]}</span><span><strong>{v.name}</strong><small>{phone(v.phone)}</small></span><span className="badge">{v.visits_count===1?'Primeira visita':'Retorno'}</span></button>)}</div>:<div className="empty"><Users size={34}/><h3>A recepção está pronta.</h3><p>Registre a primeira visita de hoje.</p><button onClick={()=>go('new')}>Cadastrar visitante</button></div>}</section></>}
 {tab==='new'&&<><div className="heading"><div><p className="eyebrow">ACOLHIMENTO</p><h1>Nova visita</h1><p>Um cadastro simples, para uma recepção mais próxima.</p></div></div><div className="form-layout"><section className="panel"><h2>Dados do visitante</h2><form onSubmit={e=>{e.preventDefault();act(async()=>{await api('/visitors','POST',form);setForm({name:'',phone:'',consent:false});setMessage('Visitante cadastrado e visita de hoje registrada.')})}}>{fields}<div className="actions"><button className="primary" disabled={busy||!online}>{busy?'Salvando…':'Salvar e registrar visita'}</button><button type="button" onClick={()=>go('visitors')}>Buscar cadastro existente</button></div></form></section><aside className="hint"><UserPlus size={32}/><h2>Já esteve aqui?</h2><p>Procure a pessoa em Visitantes e registre o retorno. Assim, todo o histórico fica no mesmo cadastro.</p><p>A data da visita é preenchida automaticamente no horário de São Paulo.</p></aside></div></>}
 {tab==='visitors'&&<><div className="heading"><div><p className="eyebrow">PESSOAS</p><h1>Visitantes</h1><p>Encontre um cadastro, consulte o histórico ou registre um retorno.</p></div><button className="primary" onClick={()=>go('new')}><UserPlus size={18}/>Nova visita</button></div><section className="panel"><label className="search"><Search size={20}/><input aria-label="Buscar visitante" placeholder="Buscar por nome ou telefone" value={query} onChange={e=>setQuery(e.target.value)}/></label><label className="followup-filter">Acompanhamento<select value={followupFilter} onChange={e=>setFollowupFilter(e.target.value)}><option value="all">Todos os visitantes</option><option value="pending">Contato pendente</option><option value="contacted">Contato realizado</option></select></label><p className="muted">Até 200 resultados. Use a busca para localizar mais pessoas.</p><div className="people">{list.filter(v=>followupFilter==='all'||(v.followup?.status||'pending')===followupFilter).map(v=><button className="person" key={v.id} onClick={()=>open(v.id)}><span className="person-avatar">{v.name[0]}</span><span><strong>{v.name}</strong><small>{phone(v.phone)}</small></span><span className="person-meta">{v.visits_count} visita(s)<small>{v.last_visit?date(v.last_visit):'Sem visita'}</small><small className={v.followup?.status==='contacted'?'contacted':'contact-pending'}>{v.followup?.status==='contacted'?'Contato realizado':'Contato pendente'}</small></span></button>)}</div>{!list.filter(v=>followupFilter==='all'||(v.followup?.status||'pending')===followupFilter).length&&<div className="empty"><Search size={30}/><h3>Nenhum visitante encontrado</h3><p>Tente outro nome ou cadastre uma nova pessoa.</p></div>}</section></>}
 {tab==='detail'&&selected&&<><button className="back" onClick={()=>go('visitors')}><ArrowLeft size={18}/>Voltar aos visitantes</button><div className="heading"><div><h1>{selected.visitor.name}</h1><p>{selected.history.length} visita(s) registrada(s)</p></div><button className="primary" disabled={busy||!online} onClick={()=>act(async()=>{await api('/visitors/'+selected.visitor.id+'/visits','POST');const d=await api('/visitors/'+selected.visitor.id);setSelected(d);setMessage('Presença de hoje confirmada.');})}><Check size={19}/>Registrar retorno hoje</button></div><div className="form-layout"><section className="panel"><h2>Cadastro</h2><form onSubmit={e=>{e.preventDefault();act(async()=>{await api('/visitors/'+selected.visitor.id,'PUT',form);setSelected(await api('/visitors/'+selected.visitor.id));setMessage('Cadastro atualizado.')})}}>{fields}<button className="primary" disabled={busy||!online}>Salvar alterações</button></form>{user.role==='admin'&&<button className="danger" disabled={busy} onClick={()=>{if(confirm('Excluir este visitante e todo o seu histórico?'))act(async()=>{await api('/visitors/'+selected.visitor.id,'DELETE');go('visitors')})}}>Excluir cadastro e histórico</button>}</section><section className="panel"><h2>Histórico de visitas</h2>{selected.history.map((h:any)=><div className="history" key={h.visit_date}><CalendarDays size={20}/><span><strong>{date(h.visit_date)}</strong><small>Recebido por {h.receptionist}</small></span></div>)}</section></div><VisitorFollowup key={selected.visitor.id} visitorId={selected.visitor.id} consent={!!selected.visitor.consent} initial={selected.visitor.followup} onSaved={async()=>{setSelected(await api('/visitors/'+selected.visitor.id))}}/></>}
 {tab==='schedule'&&<Schedule key={user.role} canEdit={['admin','team'].includes(user.role)}/>}
 {tab==='availability'&&<Availability key={user.role+user.volunteer_id} user={user}/>}
 {tab==='notices'&&<Notices key={user.id+user.volunteer_id+user.role} role={user.role}/>}
 {tab==='exports'&&user.role==='admin'&&<ExportData/>}
 {tab==='integrations'&&user.role==='admin'&&<Integrations/>}
 {tab==='team'&&user.role==='admin'&&<TeamAccess currentId={user.id}/>}
 <footer>BASE · Igreja Onda · Viva o extraordinário.</footer></main></div>}
createRoot(document.getElementById('root')!).render(<App/>);if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}));
