import React,{useEffect,useState} from 'react';
import {Heart,Pin,Pencil,Archive,Plus,RotateCcw} from 'lucide-react';
import {type NoticeView} from './noticesModel';
async function call(path='',method='GET',body?:unknown){const r=await fetch('/api/notices'+path,{method,headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const d:any=await r.json();if(!r.ok)throw Error(d.error);return d;}
const empty={title:'',body:'',pinned:false};
export function NoticeCard({notice,busy,manager,onLike,onEdit,onArchive}:{notice:NoticeView;busy:boolean;manager?:boolean;onLike:()=>void;onEdit?:()=>void;onArchive?:()=>void}){
 return <article className={`panel notice-card ${notice.pinned?'is-pinned':''}`}><div className="notice-meta">{notice.pinned&&<span><Pin size={14}/>Fixado</span>}<small>{notice.author} · {new Date(notice.created_at).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})}</small></div><h2>{notice.title}</h2><p className="notice-body">{notice.body}</p>{notice.updated_at&&<small>Editado em {new Date(notice.updated_at).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})}</small>}<div className="notice-actions"><button className={`notice-like ${notice.liked?'liked':''}`} aria-pressed={notice.liked} aria-label={`${notice.liked?'Retirar curtida':'Curtir'}: ${notice.title}. ${notice.likes_count} curtida(s)`} disabled={busy||notice.archived} onClick={onLike}><Heart size={18} fill={notice.liked?'currentColor':'none'}/><span>{notice.liked?'Curtido':'Curtir'}</span><span className="notice-like-count">{notice.likes_count}</span></button>{manager&&<div className="notice-management"><button aria-label={'Editar aviso '+notice.title} title="Editar aviso" disabled={busy||notice.archived} onClick={onEdit}><Pencil size={17}/></button><button aria-label={`${notice.archived?'Restaurar':'Arquivar'} aviso ${notice.title}`} title={notice.archived?'Restaurar':'Arquivar'} disabled={busy} onClick={onArchive}>{notice.archived?<RotateCcw size={17}/>:<Archive size={17}/>}</button></div>}</div></article>;
}
export default function Notices({role,compact=false,onOpen}:{role:string;compact?:boolean;onOpen?:()=>void}){
 const manager=['admin','team'].includes(role);
 const [items,setItems]=useState<NoticeView[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[archived,setArchived]=useState(false),[editing,setEditing]=useState<string|null>(null),[draft,setDraft]=useState(empty);
 async function refresh(){setItems((await call(archived?'?archived=1':'')).notices)}
 useEffect(()=>{let active=true;setLoading(true);setError('');call(archived?'?archived=1':'').then(d=>{if(active)setItems(d.notices)}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[archived,role]);
 async function act(fn:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await fn()}catch(e){setError(e instanceof Error?e.message:'Não foi possível concluir.')}finally{setBusy(false)}}
 return <section className={compact?'recent-notices':''}>{compact?<div className="section-title"><h2>Avisos recentes</h2><button onClick={onOpen}>Ver todos</button></div>:<div className="heading"><div><p className="eyebrow">COMUNICAÇÃO DA EQUIPE</p><h1>Quadro de avisos</h1><p>Orientações e novidades para quem serve na BASE.</p></div>{manager&&<button className="primary" disabled={busy||editing!==null} onClick={()=>{setEditing('');setDraft(empty);setNotice('')}}><Plus size={18}/>Novo aviso</button>}</div>}{!compact&&manager&&<div className="notice-tabs"><button aria-pressed={!archived} disabled={busy||editing!==null} onClick={()=>setArchived(false)}>Ativos</button><button aria-pressed={archived} disabled={busy||editing!==null} onClick={()=>setArchived(true)}>Arquivados</button></div>}{error&&<div className="alert error" role="alert">{error}</div>}{notice&&<div className="alert success" role="status">{notice}</div>}
 {editing!==null&&manager&&!compact&&<section className="panel notice-editor"><h2>{editing?'Alterar aviso':'Novo aviso'}</h2><form onSubmit={e=>{e.preventDefault();void act(async()=>{await call(editing?'/'+editing:'',editing?'PUT':'POST',draft);setEditing(null);setDraft(empty);setArchived(false);await refresh();setNotice('Aviso publicado no quadro.')})}}><label>Título<input required minLength={2} maxLength={120} disabled={busy} autoFocus value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Mensagem<textarea required maxLength={3000} rows={5} disabled={busy} value={draft.body} onChange={e=>setDraft({...draft,body:e.target.value})}/><small>{draft.body.length}/3000</small></label><label className="checkbox"><input type="checkbox" disabled={busy} checked={draft.pinned} onChange={e=>setDraft({...draft,pinned:e.target.checked})}/>Fixar no topo</label><div className="actions"><button className="primary" disabled={busy}>{busy?'Publicando…':'Publicar aviso'}</button><button type="button" disabled={busy} onClick={()=>{setEditing(null);setDraft(empty);setError('')}}>Cancelar</button></div></form></section>}
 {loading?<p className="muted" role="status">Carregando avisos…</p>:<div className="notice-list">{(compact?items.slice(0,3):items).map(item=><NoticeCard key={item.id} notice={item} busy={busy} manager={manager&&!compact} onLike={()=>void act(async()=>{await call('/'+item.id+'/like','PUT',{liked:!item.liked});await refresh()})} onEdit={()=>{setEditing(item.id);setDraft({title:item.title,body:item.body,pinned:item.pinned});setError('');setNotice('')}} onArchive={()=>{if(confirm(`${item.archived?'Restaurar':'Arquivar'} este aviso?`))void act(async()=>{await call('/'+item.id+'/archive','PUT',{archived:!item.archived});await refresh();setNotice(item.archived?'Aviso restaurado.':'Aviso arquivado.')})}}/>)}</div>}{!loading&&!items.length&&<div className="panel empty"><h3>{archived?'Nenhum aviso arquivado':'Nenhum aviso publicado'}</h3><p>{manager?'A equipe pode publicar orientações aqui.':'Os avisos da equipe aparecerão aqui.'}</p></div>}</section>;
}
